#! /bin/ash
echo "BOXLINUX SYSINIT"

set -e

run () {
	if $2 ; then
	    echo "$1 [OK]"
	else
	    echo "$1 [FAIL]"
	fi
}

date
uname -srm
run "Kernel logging" "dmesg -n2"
mkdir -p /dev/pts
run "Mounting filesystems" "mount -a"
run "Kernel settings" "sysctl -qp /etc/sysctl.conf"
run "Setting hostname" "hostname -F /etc/hostname"
run "Preparing /etc/network/if-up.d" "mkdir -p /etc/network/if-up.d"
run "Preparing /etc/network/if-pre-up.d" "mkdir -p /etc/network/if-pre-up.d"
run "Starting network" "ifup -a"
echo "Starting services ..."
echo
for service in $(ls /var/service)
do
	echo " * Starting service $service"
	runsv /var/service/$service &
done
